#!/usr/bin/env bash
#
# Build a distributable plugin package.
#
# Two packages come out of one tree, differing only by file list:
#
#   ./build.sh            GitHub release build. Uses .distignore. Contains the
#                         self-update subsystem that self-hosted installs rely
#                         on to pull new versions from GitHub releases.
#
#   ./build.sh --wporg    WordPress.org build. Uses .distignore plus
#                         .wporgignore, which strips the update subsystem.
#                         Directory guideline 8 forbids a hosted plugin from
#                         serving its own updates, so core handles them there.
#                         Choice_Universal_Form_Tracker::has_updater() detects
#                         the missing files at runtime.
#
# The two packages also use different directory names, on purpose. The GitHub
# updater matches releases against the choice-uft/ install path (see CLAUDE.md
# on release asset naming), while WordPress.org derives the slug from the
# directory and expects it to match the Text Domain header.
#
# Usage:
#   ./build.sh [--wporg] [output-dir]
#
set -euo pipefail

GITHUB_SLUG="choice-uft"
WPORG_SLUG="choice-universal-form-tracker"
SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WPORG=0
OUT=""

for arg in "$@"; do
	case "$arg" in
		--wporg) WPORG=1 ;;
		*) OUT="$arg" ;;
	esac
done
OUT="${OUT:-$SRC/dist}"

if (( WPORG )); then
	SLUG="$WPORG_SLUG"
else
	SLUG="$GITHUB_SLUG"
fi

if [[ ! -f "$SRC/.distignore" ]]; then
	echo "error: .distignore not found in $SRC" >&2
	exit 1
fi

# Real temp files rather than process substitution: an FD from <(...) is
# closed by the time an array holding it is expanded, so rsync cannot open it.
TMPDIR_BUILD="$(mktemp -d)"
trap 'rm -rf "$TMPDIR_BUILD"' EXIT

grep -vE '^[[:space:]]*#|^[[:space:]]*$' "$SRC/.distignore" > "$TMPDIR_BUILD/dist"
EXCLUDES=( --exclude-from="$TMPDIR_BUILD/dist" )
if (( WPORG )); then
	if [[ ! -f "$SRC/.wporgignore" ]]; then
		echo "error: --wporg requested but .wporgignore not found in $SRC" >&2
		exit 1
	fi
	grep -vE '^[[:space:]]*#|^[[:space:]]*$' "$SRC/.wporgignore" > "$TMPDIR_BUILD/wporg"
	EXCLUDES+=( --exclude-from="$TMPDIR_BUILD/wporg" )
fi

rm -rf "${OUT:?}/$SLUG" "${OUT:?}/$SLUG.zip"
mkdir -p "$OUT/$SLUG"

rsync -a "${EXCLUDES[@]}" --exclude='dist/' "$SRC/" "$OUT/$SLUG/"

# rsync recreates a directory even when every file in it was excluded.
find "$OUT/$SLUG" -mindepth 1 -type d -empty -delete

( cd "$OUT" && zip -qr "$SLUG.zip" "$SLUG" )

echo "built: $OUT/$SLUG"
echo "       $OUT/$SLUG.zip"
if (( WPORG )); then
	echo "       (WordPress.org build: no self-update subsystem)"
else
	echo "       (GitHub build: self-update subsystem included)"
fi
echo
echo "contents:"
find "$OUT/$SLUG" -type f | sed "s|$OUT/$SLUG/|  |" | sort

fail=0

# The three version sources must agree or WordPress.org rejects the upload.
hdr_version=$(sed -n 's/^ \* Version:[[:space:]]*\(.*\)$/\1/p' "$OUT/$SLUG/choice-universal-form-tracker.php" | head -1 | tr -d '[:space:]')
const_version=$(sed -n "s/.*define( 'CUFT_VERSION', '\([^']*\)' );.*/\1/p" "$OUT/$SLUG/choice-universal-form-tracker.php" | head -1)
stable_tag=$(sed -n 's/^Stable tag:[[:space:]]*\(.*\)$/\1/p' "$OUT/$SLUG/readme.txt" | head -1 | tr -d '[:space:]')

echo
echo "versions: header=$hdr_version constant=$const_version stable-tag=$stable_tag"
if [[ "$hdr_version" != "$const_version" || "$hdr_version" != "$stable_tag" ]]; then
	echo "error: Version header, CUFT_VERSION, and readme.txt Stable tag must agree" >&2
	fail=1
fi

# WordPress.org rejects packages containing hidden files.
if find "$OUT/$SLUG" -name '.*' -not -name '.' | grep -q .; then
	echo >&2
	echo "error: hidden files present in the package; WordPress.org rejects these" >&2
	find "$OUT/$SLUG" -name '.*' -not -name '.' >&2
	fail=1
fi

# House rule: no em-dash in any shipped artifact.
#
# gtm-server/ and gtm-web-client/ are exempt. They hold container exports and a
# tag template generated by Google Tag Manager, and the em-dashes in them sit
# inside Google's own field help text. Editing that copy would alter a
# machine-generated file that has to import back into GTM unchanged, and it is
# vendor content rather than anything written here.
if LC_ALL=C grep -rlI $'\xe2\x80\x94' "$OUT/$SLUG" \
	--exclude-dir=gtm-server --exclude-dir=gtm-web-client | grep -q .; then
	echo >&2
	echo "error: em-dash (U+2014) present in shipped files" >&2
	LC_ALL=C grep -rlI $'\xe2\x80\x94' "$OUT/$SLUG" \
		--exclude-dir=gtm-server --exclude-dir=gtm-web-client >&2
	fail=1
fi

if (( WPORG )); then
	# Guideline 8: nothing that serves the plugin its own updates may ship.
	if find "$OUT/$SLUG" -name '*github*' -o -name '*updater*' -o -name '*force-update*' | grep -q .; then
		echo >&2
		echo "error: self-update files reached the WordPress.org package" >&2
		find "$OUT/$SLUG" \( -name '*github*' -o -name '*updater*' -o -name '*force-update*' \) >&2
		fail=1
	fi
	# Guideline 8 again: all non-service JavaScript and CSS must be local.
	if LC_ALL=C grep -rlIE 'cdnjs\.cloudflare\.com|unpkg\.com|jsdelivr\.net|ajax\.googleapis\.com' "$OUT/$SLUG" | grep -q .; then
		echo >&2
		echo "error: third-party CDN reference in the WordPress.org package" >&2
		LC_ALL=C grep -rlIE 'cdnjs\.cloudflare\.com|unpkg\.com|jsdelivr\.net|ajax\.googleapis\.com' "$OUT/$SLUG" >&2
		fail=1
	fi
fi

exit "$fail"
